version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zip-a-folder
    versions:
    - 0.1.0
    - 1.0.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
